// <auto-generated />
using System;
using ApiaryServer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiaryServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Apiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Apiaries");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmationTokens");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Hive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RameAlbine")
                        .HasColumnType("int");

                    b.Property<int>("RameMiere")
                        .HasColumnType("int");

                    b.Property<int>("RamePuiet")
                        .HasColumnType("int");

                    b.Property<bool>("ReginaPrezenta")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UltimaInspectie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VarstaRegina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.ToTable("Hives");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.HiveExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExtractionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("ExtractionDate");

                    b.HasIndex("HiveId");

                    b.ToTable("HiveExtractions");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.HiveTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("HiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("HiveId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DueDate");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.HiveTreatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("NextTreatmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Substance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TreatmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("HiveId");

                    b.HasIndex("TreatmentDate");

                    b.ToTable("HiveTreatments");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BeardingAtEntrance")
                        .HasColumnType("bit");

                    b.Property<int?>("BroodFrames")
                        .HasColumnType("int");

                    b.Property<string>("BroodPattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeadBeesAtEntrance")
                        .HasColumnType("bit");

                    b.Property<bool>("EggsSeen")
                        .HasColumnType("bit");

                    b.Property<bool>("FeedingGiven")
                        .HasColumnType("bit");

                    b.Property<int?>("FramesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("HiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HoneyCappingPercent")
                        .HasColumnType("int");

                    b.Property<int?>("HoneyFrames")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("InspectionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LarvaeSeen")
                        .HasColumnType("bit");

                    b.Property<bool>("MoistureOrMold")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldCombsToReplace")
                        .HasColumnType("int");

                    b.Property<int?>("PollenFrames")
                        .HasColumnType("int");

                    b.Property<bool>("QueenCellsSeen")
                        .HasColumnType("bit");

                    b.Property<bool>("QueenCellsWithEggs")
                        .HasColumnType("bit");

                    b.Property<bool>("QueenSeen")
                        .HasColumnType("bit");

                    b.Property<bool>("SpaceNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("Temperament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("UnusualBehavior")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("WaterAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("HiveId");

                    b.HasIndex("InspectionDate");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.InspectionAiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BroodCells")
                        .HasColumnType("int");

                    b.Property<decimal?>("BroodDensity")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("CappedBroodCells")
                        .HasColumnType("int");

                    b.Property<string>("CellDetectionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EggsCells")
                        .HasColumnType("int");

                    b.Property<int>("EmptyCells")
                        .HasColumnType("int");

                    b.Property<Guid>("HiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HoneyCells")
                        .HasColumnType("int");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LarvaeCells")
                        .HasColumnType("int");

                    b.Property<decimal?>("LarvaeToCappedRatio")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherCells")
                        .HasColumnType("int");

                    b.Property<int>("PollenCells")
                        .HasColumnType("int");

                    b.Property<string>("RawResultsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoresCells")
                        .HasColumnType("int");

                    b.Property<decimal?>("StoresRatio")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("TotalCells")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("InspectionId");

                    b.HasIndex("HiveId", "CreatedAt");

                    b.ToTable("InspectionAiAnalyses");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.InspectionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("InspectionPhotos");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByJti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Apiary", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.EmailConfirmationToken", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.User", "User")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Hive", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Apiary", "Apiary")
                        .WithMany("Hives")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.HiveExtraction", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Apiary", "Apiary")
                        .WithMany("Extractions")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiaryServer.Domain.Entities.Hive", "Hive")
                        .WithMany("Extractions")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.HiveTask", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Apiary", "Apiary")
                        .WithMany("Tasks")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApiaryServer.Domain.Entities.Hive", "Hive")
                        .WithMany("Tasks")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApiaryServer.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");

                    b.Navigation("Hive");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.HiveTreatment", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Apiary", "Apiary")
                        .WithMany("Treatments")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiaryServer.Domain.Entities.Hive", "Hive")
                        .WithMany("Treatments")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Inspection", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Apiary", "Apiary")
                        .WithMany("Inspections")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiaryServer.Domain.Entities.Hive", "Hive")
                        .WithMany("Inspections")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.InspectionAiAnalysis", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Apiary", "Apiary")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiaryServer.Domain.Entities.Hive", "Hive")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiaryServer.Domain.Entities.Inspection", "Inspection")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");

                    b.Navigation("Hive");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.InspectionPhoto", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.Inspection", "Inspection")
                        .WithMany("Photos")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ApiaryServer.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Apiary", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("Extractions");

                    b.Navigation("Hives");

                    b.Navigation("Inspections");

                    b.Navigation("Tasks");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Hive", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("Extractions");

                    b.Navigation("Inspections");

                    b.Navigation("Tasks");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.Inspection", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ApiaryServer.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
